category_regex_rules:
  Groceries:
    - 'H-E-B #'
    - 99 RANCH
    - PETCO
  Administrative:
    - Amazon Prime
    - LEMONADE
    - Google Storage
  Amortized:
    - Audible
  Amazon:
    - AMZN Mktp
    - Amazon.com
  Discretionary:
    - SIGNAL FOUNDATION SIGNAL.ORG
  Transportation:
    - UBER
    - LYFT
    - SHELL OIL
    - H-E-B GAS
  Inflows:
    - DEPOSIT ACH AKUNA INVESTMENT
    - Bank of America DES:CASHREWARD
    - DEPOSIT DIVIDEND
    - Interest Earned
  Transfers to Non-Cash Accounts:
    - SCHWAB BROKERAGE DES:MONEYLINK
    - 'WITHDRAWAL ACH TYPE: TRANSFER ID: LENDINGCLUB BANK'
  zzz_Discard:
    - Beginning balance
    - ALLIANT CU DES:XFER
    - CHASE CREDIT CRD DES:EPAY
    - Bank of America Credit Card Bill Payment
    - 'WITHDRAWAL ACH TYPE: TRANSFER ID: BANK OF AMERICA'
    - Payment Thank You
    - PAYMENT - THANK YOU
  Eating Out:
    - 'TST\*'
    - 'SQ \*'
    - TORCHYS MUELLER
    - KISMET CAFE
    - BLACKSBBQ
    - BOMBAY TO KATHMANDU
    - LUPE TORTILLA
    - NORTH ITALIA
    - P. TERRY'S
    - RUTH'S CHRIS
    - SAPS FINE THAI
    - SNOOZE
    - WATTS THAT SOUL FOOD

